### ISSUE TITLE
HTTPS update!

### ISSUE THREAD

**Issue by xgqfrms007** [xgqfrms/xgqfrms#7]
HTTPS update!

https://shields.io/

![https://shields.io/logo.svg](https://shields.io/logo.svg)

# github Icons

[![GitHub forks](https://img.shields.io/github/forks/xgqfrms/xgqfrms.svg?style=social&label=Fork&)](https://github.com/xgqfrms/xgqfrms)
[![GitHub stars](https://img.shields.io/github/stars/xgqfrms/xgqfrms.svg?style=social&label=Star&)](https://github.com/xgqfrms/xgqfrms)
[![GitHub watchers](https://img.shields.io/github/watchers/xgqfrms/xgqfrms.svg?style=social&label=Watch&)](https://github.com/xgqfrms/xgqfrms)
[![GitHub followers](https://img.shields.io/github/followers/xgqfrms.svg?style=social&label=Follow&)](https://github.com/xgqfrms)

**Comment by xgqfrms** [comment]
# OK, but partly error!

Main domain error!  
https://www.xgqfrms.xyz  

Sub domain OK!  
https://es6.xgqfrms.xyz  

@xgqfrms007
